### ISSUE TITLE
go thru CPY .gitignore to add files to ignore

### ISSUE THREAD

**Issue by axelmagnus** [johnwargo/circuitpython-sync#1]
Hello, and **thanks** for an easy solution to a problem i've struggled with!

For us Mac user there is definitely a file that we want to add to the ignore list:
**DS_store**
that is created for some reason or another. 

There are others (files that are created when drag-dropping in finder), and i guess youve already looked at [prevent-and-remove-macos-hidden-files](https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#prevent-and-remove-macos-hidden-files-2978468) (if your thing could incorporate that script to prevent this would be another nice thing :) ).

when I was thinking about this, an idea sprang to mind. I add DS_store, secrets.py, settings.toml etc to my .gitignore since i dont want to share passwords on github. Why not have youre code go thru the .gitignore on the CPY and ignore those too? It would be an easy way to add/delete any file to this list... Thinking more about it, i realise that sometimes you _do_ wanna backup your secrets.py on the local hard drive (and have _its_ .gitignore exclude these files on github), so maybe an option to include CPY's .gitignore files or not is wanted (or you just keep track of it by adding/deleting in .gitignore?).

one last thing:
youre idea is so good, shouldnt it be part of the [Circuitpython VS code extension](https://github.com/joedevivo/vscode-circuitpython)?

Thanks again!

**Comment by johnwargo** [comment]
@axelmagnus yeah, that's a great idea. My primary code editing system Windows, so I'd not considered the macOS use case. 

I can easily add the `DS_store` file to the ignored file list, but this is something you could do too then submit a pull request. All it takes is a quick addition to the following array in the code:

```javascript
const ignoreFiles = [
  'boot_out.txt',
  'BOOTEX.LOG',
  '.metadata_never_index',
  'System Volume Information',
  'test_results.txt',
  '.Trashes'
] as const;
```

I'll make the change now. 

Regarding the script, since the utility runs on linux, macOS, and Windows, adding that macOS-specific script would not be useful for all users. I prefer to let that kind of thing to the user if they want to implement it. 

For the Visual Studio Code extension, I looked at it when I first started looking for solutions and it felt like that extension was going a different direction than what I was looking for.

**Comment by johnwargo** [comment]
implemented
